# Hexo 站点配置模板
# 详情请参阅: https://hexo.io/docs/configuration

# 网站信息
title: Jane's Blog 
subtitle: ''
description: '记录成长与思考'
keywords:
author: Jane
language: zh-CN
timezone: 'Asia/Shanghai'

# 网址设置
# 如果你的博客部署在子目录中，请将 root 设置为 '/project/'
url: http://example.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # 是否在 URL 中保留 'index.html'
  trailing_html: true # 是否在 URL 中保留 '.html'

# 目录设置
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作设置
new_post_name: :title.md # 新文章的文件名格式
default_layout: post
titlecase: false # 转换标题为大写
external_link:
  enable: true # 在新标签中打开外部链接
  field: site # 作用范围: site (整个站点) 或 post (仅文章)
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# 分类与标签
default_category: uncategorized
category_map:
tag_map:

# 元数据 (日期 / 时间 格式)
# Hexo 使用 Moment.js 解析和显示日期
# 详情: http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## 使用 updated_option 决定如何显示文章更新时间
## 选项: mtime (文件最后修改时间), date (文章创建日期), empty (不显示)
updated_option: 'mtime'

# 分页设置
per_page: 10
pagination_dir: page

# 包含 / 排除
include:
exclude:
ignore:

# 扩展 (主题与插件)
# 主题设置，此处推荐使用 butterfly
theme: butterfly

# 部署设置
# 详情: https://hexo.io/docs/deployment.html
deploy:
  type: ''
