name: Hexo Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 监控 main 分支推送

# 赋予部署 GitHub Pages 所需的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 部署环境
environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and Generate
        run: |
          touch source/.nojekyll
          npx hexo clean
          npx hexo generate

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public # Hexo 生成的静态文件目录

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
